apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automotive-car
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - ui.yaml
  - nginx.yaml
  - thingsboard.yaml
