apiVersion: v1
kind: Service
metadata:
  name: thingsboard
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30090
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: edge-rpc
      port: 7070
      targetPort: 7070
      nodePort: 30070
    - name: coap
      port: 5683
      targetPort: 5683
      nodePort: 30683
      protocol: UDP
